#pragma once

#define IPL_VERSION_EPOCH    0
#define IPL_VERSION_MAJOR    1
#define IPL_VERSION_MINOR    0
#define IPL_VERSION_REVISION 0

#define IPLAUX_STR_EXP(__A)  #__A
#define IPLAUX_STR(__A)      IPLAUX_STR_EXP(__A)

#define IPLAUX_STRW_EXP(__A)  L#__A
#define IPLAUX_STRW(__A)      IPLAUX_STRW_EXP(__A)

#if IPL_VERSION_REVISION
#  define IPL_VERSION        IPLAUX_STR(IPL_VERSION_EPOCH) "." IPLAUX_STR(IPL_VERSION_MAJOR) "." IPLAUX_STR(IPL_VERSION_MINOR) "." IPLAUX_STR(IPL_VERSION_REVISION)
#else
#  define IPL_VERSION        IPLAUX_STR(IPL_VERSION_EPOCH) "." IPLAUX_STR(IPL_VERSION_MAJOR) "." IPLAUX_STR(IPL_VERSION_MINOR)
#endif

/* old  style version constants*/
#define IPL_MAJOR_VERSION    IPL_VERSION_EPOCH
#define IPL_MINOR_VERSION    IPL_VERSION_MAJOR
#define IPL_SUBMINOR_VERSION IPL_VERSION_MINOR

